/**
 * Paediatric tox triage — substance database (educational; verify with TOXBASE/NPIS).
 * strength_mg + unit: per_5ml | per_ml | tablet | elemental_tablet (iron)
 */
var SUBSTANCES = [
  { id: 'paracetamol', name: 'Paracetamol (acetaminophen)', aliases: ['paracetamol', 'acetaminophen', 'calpol', 'panadol', 'pamol'], category: 'Analgesics',
    formulations: [
      { name: '120mg/5ml liquid', strength_mg: 120, unit: 'per_5ml' },
      { name: '250mg/5ml liquid', strength_mg: 250, unit: 'per_5ml' },
      { name: '500mg tablet', strength_mg: 500, unit: 'tablet' },
      { name: '1g tablet', strength_mg: 1000, unit: 'tablet' },
      { name: '250mg suppository', strength_mg: 250, unit: 'tablet' }
    ],
    toxic_dose_mg_per_kg: 150, serious_dose_mg_per_kg: 200, lethal_dose_mg_per_kg: null,
    antidote: 'N-acetylcysteine (NAC)', antidote_fn: 'nac',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 4, observation_hrs_high: 24,
    npis_criteria: ['Staggered ingestion', 'Modified release uncertain', 'Level near line', 'Vomiting preventing care'],
    key_features_to_monitor: ['LFTs', 'INR', 'renal function', 'acidosis'],
    risk_notes: 'Common serious paediatric ingestion; use nomogram for levels.',
    modified_release_available: true, investigation_profile: 'paracetamol', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'ibuprofen', name: 'Ibuprofen', aliases: ['ibuprofen', 'nurofen', 'brufen'], category: 'Analgesics',
    formulations: [
      { name: '100mg/5ml liquid', strength_mg: 100, unit: 'per_5ml' },
      { name: '200mg tablet', strength_mg: 200, unit: 'tablet' },
      { name: '400mg tablet', strength_mg: 400, unit: 'tablet' },
      { name: '600mg tablet', strength_mg: 600, unit: 'tablet' }
    ],
    toxic_dose_mg_per_kg: 100, serious_dose_mg_per_kg: 400, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 4, observation_hrs_high: 8,
    npis_criteria: ['Large ingestion', 'Symptomatic', 'Renal concern'],
    key_features_to_monitor: ['GI bleeding', 'renal function', 'CNS depression'],
    risk_notes: '>400mg/kg serious; supportive care usually.',
    modified_release_available: false, investigation_profile: 'nsaid', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'aspirin', name: 'Aspirin / salicylates', aliases: ['aspirin', 'salicylate', 'salicylic', 'disprin'], category: 'Analgesics',
    formulations: [
      { name: '75mg tablet', strength_mg: 75, unit: 'tablet' },
      { name: '300mg tablet', strength_mg: 300, unit: 'tablet' }
    ],
    toxic_dose_mg_per_kg: 150, serious_dose_mg_per_kg: 250, lethal_dose_mg_per_kg: 500,
    antidote: 'Urinary alkalinisation / supportive (no specific antidote)', antidote_fn: 'salicylate_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: 'salicylate',
    specific_questions: [], observation_hrs_low: 6, observation_hrs_high: 24,
    npis_criteria: ['Serum salicylate rising', 'Acidosis', 'Pulmonary oedema', 'CNS signs'],
    key_features_to_monitor: ['ABG', 'glucose', 'salicylate level', 'fluid balance'],
    risk_notes: 'Toxic at ~150mg/kg; metabolic acidosis risk.',
    modified_release_available: false, investigation_profile: 'salicylate', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'codeine', name: 'Codeine', aliases: ['codeine', 'codeine phosphate'], category: 'Analgesics',
    formulations: [{ name: '15mg/5ml liquid', strength_mg: 15, unit: 'per_5ml' }, { name: '30mg tablet', strength_mg: 30, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 1, serious_dose_mg_per_kg: 2, lethal_dose_mg_per_kg: null,
    antidote: 'Naloxone', antidote_fn: 'naloxone',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 6, observation_hrs_high: 12,
    npis_criteria: ['Respiratory depression', 'Reduced GCS', 'CYP2D6 ultra-rapid metaboliser concern'],
    key_features_to_monitor: ['RR', 'GCS', 'miosis'],
    risk_notes: 'Opioid toxidrome; ultra-metabolisers at higher risk.',
    modified_release_available: false, investigation_profile: 'opioid', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'tramadol', name: 'Tramadol', aliases: ['tramadol', 'zydol'], category: 'Analgesics',
    formulations: [{ name: '50mg capsule', strength_mg: 50, unit: 'tablet' }, { name: '100mg tablet (SR)', strength_mg: 100, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 5, serious_dose_mg_per_kg: 10, lethal_dose_mg_per_kg: null,
    antidote: 'Naloxone (partial reversal)', antidote_fn: 'naloxone',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 6, observation_hrs_high: 12,
    npis_criteria: ['Seizure', 'Serotonin features with co-ingestants'],
    key_features_to_monitor: ['Seizures', 'respiratory depression', 'QT'],
    risk_notes: 'Lowers seizure threshold; serotonin risk with SSRIs.',
    modified_release_available: true, investigation_profile: 'opioid', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'metformin', name: 'Metformin', aliases: ['metformin', 'glucophage'], category: 'Prescription',
    formulations: [{ name: '500mg tablet', strength_mg: 500, unit: 'tablet' }, { name: '850mg tablet', strength_mg: 850, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: 100, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 24,
    npis_criteria: ['Large ingestion', 'Acidosis', 'AKI', 'lactate raised'],
    key_features_to_monitor: ['VBG/lactate', 'renal function', 'glucose'],
    risk_notes: 'Lactic acidosis; large ingestions may need PICU.',
    modified_release_available: true, investigation_profile: 'metformin', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'amlodipine', name: 'Amlodipine', aliases: ['amlodipine', 'istin'], category: 'Prescription',
    formulations: [{ name: '5mg tablet', strength_mg: 5, unit: 'tablet' }, { name: '10mg tablet', strength_mg: 10, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 0.3, serious_dose_mg_per_kg: 0.5, lethal_dose_mg_per_kg: null,
    antidote: 'Calcium / glucagon / lipids — per NPIS', antidote_fn: 'ccb_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Hypotension', 'bradycardia', 'shock'],
    key_features_to_monitor: ['BP', 'HR', 'ECG'],
    risk_notes: 'CCB: small doses can cause profound hypotension in children.',
    modified_release_available: false, investigation_profile: 'ccb', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'nifedipine', name: 'Nifedipine', aliases: ['nifedipine', 'adalat'], category: 'Prescription',
    formulations: [{ name: '5mg capsule', strength_mg: 5, unit: 'tablet' }, { name: '10mg capsule', strength_mg: 10, unit: 'tablet' }, { name: 'Modified release', strength_mg: 60, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 0.3, serious_dose_mg_per_kg: 0.5, lethal_dose_mg_per_kg: null,
    antidote: 'As per NPIS (calcium, glucagon, lipids)', antidote_fn: 'ccb_note',
    decontamination_eligible: true, decontamination_window_hrs: 2, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Hypotension', 'bradycardia'],
    key_features_to_monitor: ['BP', 'HR', 'glucose'],
    risk_notes: 'MR formulations prolong absorption.',
    modified_release_available: true, investigation_profile: 'ccb', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'bisoprolol', name: 'Bisoprolol', aliases: ['bisoprolol'], category: 'Prescription',
    formulations: [{ name: '2.5mg tablet', strength_mg: 2.5, unit: 'tablet' }, { name: '5mg tablet', strength_mg: 5, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 0.5, serious_dose_mg_per_kg: 1, lethal_dose_mg_per_kg: null,
    antidote: 'Glucagon / adrenaline — per NPIS', antidote_fn: 'bb_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Bradycardia', 'hypotension', 'hypoglycaemia', 'seizures'],
    key_features_to_monitor: ['ECG', 'glucose', 'BP'],
    risk_notes: 'Beta-blocker: bradycardia and hypoglycaemia.',
    modified_release_available: false, investigation_profile: 'bb', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'atenolol', name: 'Atenolol', aliases: ['atenolol', 'tenormin'], category: 'Prescription',
    formulations: [{ name: '25mg tablet', strength_mg: 25, unit: 'tablet' }, { name: '50mg tablet', strength_mg: 50, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 0.5, serious_dose_mg_per_kg: 1, lethal_dose_mg_per_kg: null,
    antidote: 'Glucagon / adrenaline — per NPIS', antidote_fn: 'bb_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Bradycardia', 'hypotension', 'hypoglycaemia'],
    key_features_to_monitor: ['ECG', 'glucose'],
    risk_notes: '',
    modified_release_available: false, investigation_profile: 'bb', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'amitriptyline', name: 'Amitriptyline', aliases: ['amitriptyline', 'triptafen'], category: 'Prescription',
    formulations: [{ name: '10mg tablet', strength_mg: 10, unit: 'tablet' }, { name: '25mg tablet', strength_mg: 25, unit: 'tablet' }, { name: '50mg tablet', strength_mg: 50, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 5, serious_dose_mg_per_kg: 10, lethal_dose_mg_per_kg: null,
    antidote: 'Sodium bicarbonate for wide QRS — discuss NPIS', antidote_fn: 'tca_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Any symptomatic child', 'QRS widening', 'seizures', 'arrhythmia'],
    key_features_to_monitor: ['ECG QRS/QT', 'GCS', 'seizures'],
    risk_notes: 'TCA: any childhood ingestion — discuss NPIS.',
    modified_release_available: false, investigation_profile: 'tca', tca: true, npis_immediate: true, high_risk_substance: true
  },
  { id: 'sertraline', name: 'Sertraline', aliases: ['sertraline', 'lustral'], category: 'Prescription',
    formulations: [{ name: '50mg tablet', strength_mg: 50, unit: 'tablet' }, { name: '100mg tablet', strength_mg: 100, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 5, serious_dose_mg_per_kg: 15, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 6, observation_hrs_high: 12,
    npis_criteria: ['Serotonin syndrome', 'seizures'],
    key_features_to_monitor: ['HR', 'temperature', 'clonus'],
    risk_notes: 'SSRIs: usually low risk small doses; serotonin syndrome with MAOI/serotonergics.',
    modified_release_available: false, investigation_profile: 'ssri', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'fluoxetine', name: 'Fluoxetine', aliases: ['fluoxetine', 'prozac'], category: 'Prescription',
    formulations: [{ name: '20mg capsule', strength_mg: 20, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 5, serious_dose_mg_per_kg: 15, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 6, observation_hrs_high: 12,
    npis_criteria: ['Serotonin syndrome'],
    key_features_to_monitor: ['HR', 'temperature', 'agitation'],
    risk_notes: 'Long half-life.',
    modified_release_available: false, investigation_profile: 'ssri', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'quetiapine', name: 'Quetiapine', aliases: ['quetiapine', 'seroquel'], category: 'Prescription',
    formulations: [{ name: '25mg tablet', strength_mg: 25, unit: 'tablet' }, { name: '100mg tablet', strength_mg: 100, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 5, serious_dose_mg_per_kg: 20, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 12,
    npis_criteria: ['QT prolongation', 'coma', 'seizures'],
    key_features_to_monitor: ['ECG', 'GCS'],
    risk_notes: 'Sedation, orthostasis, QT.',
    modified_release_available: true, investigation_profile: 'sedating', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'olanzapine', name: 'Olanzapine', aliases: ['olanzapine', 'zyprexa'], category: 'Prescription',
    formulations: [{ name: '5mg tablet', strength_mg: 5, unit: 'tablet' }, { name: '10mg tablet', strength_mg: 10, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 0.5, serious_dose_mg_per_kg: 1, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 12,
    npis_criteria: ['Neuroleptic malignant syndrome features'],
    key_features_to_monitor: ['temperature', 'GCS', 'rigidity'],
    risk_notes: '',
    modified_release_available: false, investigation_profile: 'sedating', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'melatonin', name: 'Melatonin', aliases: ['melatonin', 'circadin'], category: 'Prescription',
    formulations: [{ name: '2mg tablet', strength_mg: 2, unit: 'tablet' }, { name: '3mg tablet', strength_mg: 3, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 10, serious_dose_mg_per_kg: 30, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 2, observation_hrs_high: 4,
    npis_criteria: ['Paradoxical agitation'],
    key_features_to_monitor: ['sedation'],
    risk_notes: 'Generally low toxicity in accidental paediatric doses.',
    modified_release_available: false, investigation_profile: 'general', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'methadone', name: 'Methadone', aliases: ['methadone', 'physeptone'], category: 'Prescription',
    formulations: [{ name: '5mg/5ml liquid', strength_mg: 5, unit: 'per_5ml' }, { name: '10mg tablet', strength_mg: 10, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 0.05, serious_dose_mg_per_kg: 0.1, lethal_dose_mg_per_kg: null,
    antidote: 'Naloxone', antidote_fn: 'naloxone',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Any suspected ingestion in child'],
    key_features_to_monitor: ['RR', 'GCS', 'miosis'],
    risk_notes: 'Extremely dangerous; small doses can be lethal in opioid-naive child.',
    modified_release_available: false, investigation_profile: 'opioid', tca: false, npis_immediate: true, high_risk_substance: true
  },
  { id: 'clonidine', name: 'Clonidine', aliases: ['clonidine', 'catapres'], category: 'Prescription',
    formulations: [{ name: '25mcg tablet (0.025mg)', strength_mg: 0.025, unit: 'tablet' }, { name: '100mcg tablet (0.1mg)', strength_mg: 0.1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 0.01, serious_dose_mg_per_kg: 0.02, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: 'clonidine_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 12,
    npis_criteria: ['Bradycardia', 'hypotension', 'altered consciousness'],
    key_features_to_monitor: ['HR', 'BP', 'GCS'],
    risk_notes: 'Alpha-2 agonist; toxicity at low doses in children — easily missed.',
    modified_release_available: false, investigation_profile: 'general', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'lithium', name: 'Lithium', aliases: ['lithium', 'priadel'], category: 'Prescription',
    formulations: [{ name: '200mg tablet (as carbonate)', strength_mg: 200, unit: 'tablet' }, { name: '400mg tablet', strength_mg: 400, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: 'lithium_note',
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Acute vs chronic context', 'tremor', 'CK', 'renal impairment'],
    key_features_to_monitor: ['U&E', 'lithium level', 'hydration'],
    risk_notes: 'Charcoal poor adsorption; chronic vs acute differs — NPIS.',
    modified_release_available: false, investigation_profile: 'lithium', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'valproate', name: 'Sodium valproate', aliases: ['valproate', 'valproic', 'epilim', 'depakote'], category: 'Prescription',
    formulations: [{ name: '200mg tablet', strength_mg: 200, unit: 'tablet' }, { name: '500mg tablet', strength_mg: 500, unit: 'tablet' }, { name: '200mg/5ml liquid', strength_mg: 200, unit: 'per_5ml' }],
    toxic_dose_mg_per_kg: 100, serious_dose_mg_per_kg: 200, lethal_dose_mg_per_kg: null,
    antidote: 'L-carnitine in severe cases — NPIS', antidote_fn: 'valproate_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 12,
    npis_criteria: ['Encephalopathy', 'hyperammonaemia', 'liver dysfunction'],
    key_features_to_monitor: ['LFTs', 'ammonia', 'glucose'],
    risk_notes: 'Hepatotoxicity risk.',
    modified_release_available: true, investigation_profile: 'valproate', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'phenytoin', name: 'Phenytoin', aliases: ['phenytoin', 'epanutin'], category: 'Prescription',
    formulations: [{ name: '25mg/5ml suspension', strength_mg: 25, unit: 'per_5ml' }, { name: '100mg capsule', strength_mg: 100, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 20, serious_dose_mg_per_kg: 40, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 12,
    npis_criteria: ['Ataxia', 'nystagmus', 'arrhythmia'],
    key_features_to_monitor: ['ECG', 'phenytoin level'],
    risk_notes: 'Enzyme inducer — paracetamol interaction context.',
    modified_release_available: false, investigation_profile: 'anticonvulsant', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'carbamazepine', name: 'Carbamazepine', aliases: ['carbamazepine', 'tegretol'], category: 'Prescription',
    formulations: [{ name: '100mg tablet', strength_mg: 100, unit: 'tablet' }, { name: '200mg tablet', strength_mg: 200, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 20, serious_dose_mg_per_kg: 40, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 2, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 12,
    npis_criteria: ['Arrhythmia', 'seizures', 'coma'],
    key_features_to_monitor: ['ECG', 'level'],
    risk_notes: 'MR preparations prolong absorption.',
    modified_release_available: true, investigation_profile: 'anticonvulsant', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'warfarin', name: 'Warfarin', aliases: ['warfarin', 'marevan'], category: 'Prescription',
    formulations: [{ name: '1mg tablet', strength_mg: 1, unit: 'tablet' }, { name: '3mg tablet', strength_mg: 3, unit: 'tablet' }, { name: '5mg tablet', strength_mg: 5, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 0.5, serious_dose_mg_per_kg: 1, lethal_dose_mg_per_kg: null,
    antidote: 'Vitamin K / PCC — per NPIS', antidote_fn: 'warfarin_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 24, observation_hrs_high: 48,
    npis_criteria: ['Bleeding', 'large ingestion'],
    key_features_to_monitor: ['INR', 'bleeding'],
    risk_notes: 'Delayed effect — INR monitoring.',
    modified_release_available: false, investigation_profile: 'anticoag', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'doac', name: 'DOAC (dabigatran/apixaban/rivaroxaban)', aliases: ['dabigatran', 'apixaban', 'rivaroxaban', 'xarelto', 'eliquis', 'pradaxa'], category: 'Prescription',
    formulations: [{ name: 'Representative 5mg tablet', strength_mg: 5, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: 'Specific reversal per NPIS', antidote_fn: 'doac_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Bleeding', 'renal impairment'],
    key_features_to_monitor: ['renal function', 'bleeding'],
    risk_notes: 'Agent-specific management.',
    modified_release_available: false, investigation_profile: 'anticoag', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'verapamil', name: 'Verapamil', aliases: ['verapamil'], category: 'Prescription',
    formulations: [{ name: '40mg tablet', strength_mg: 40, unit: 'tablet' }, { name: '120mg MR', strength_mg: 120, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 1, serious_dose_mg_per_kg: 3, lethal_dose_mg_per_kg: null,
    antidote: 'As per NPIS', antidote_fn: 'ccb_note',
    decontamination_eligible: true, decontamination_window_hrs: 2, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Heart block', 'hypotension'],
    key_features_to_monitor: ['ECG', 'BP'],
    risk_notes: 'MR alters kinetics.',
    modified_release_available: true, investigation_profile: 'ccb', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'morphine', name: 'Morphine', aliases: ['morphine', 'oramorph', 'sevredol'], category: 'Prescription',
    formulations: [{ name: '10mg/5ml liquid', strength_mg: 10, unit: 'per_5ml' }, { name: '10mg tablet', strength_mg: 10, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 0.2, serious_dose_mg_per_kg: 0.5, lethal_dose_mg_per_kg: null,
    antidote: 'Naloxone', antidote_fn: 'naloxone',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 12,
    npis_criteria: ['Respiratory depression'],
    key_features_to_monitor: ['RR', 'GCS'],
    risk_notes: 'MR preparations prolong absorption.',
    modified_release_available: true, investigation_profile: 'opioid', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'pods', name: 'Dishwasher/laundry detergent pods', aliases: ['pod', 'capsule detergent', 'laundry capsule'], category: 'Household',
    formulations: [{ name: 'Unknown (estimate ml)', strength_mg: 1, unit: 'per_ml' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: true, hydrocarbon: false, special: 'caustic',
    specific_questions: [], observation_hrs_low: 4, observation_hrs_high: 12,
    npis_criteria: ['Stridor', 'drooling', 'oral burns', 'respiratory distress'],
    key_features_to_monitor: ['airway', 'swallow assessment'],
    risk_notes: 'Caustic; NO charcoal; endoscopy thresholds per NPIS.',
    modified_release_available: false, investigation_profile: 'caustic', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'bleach', name: 'Bleach (sodium hypochlorite &lt;10%)', aliases: ['bleach', 'hypochlorite', 'domestos dilute'], category: 'Household',
    formulations: [{ name: 'Volume ingested (ml)', strength_mg: 1, unit: 'per_ml' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: true, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 2, observation_hrs_high: 6,
    npis_criteria: ['Concentrated product', 'persistent vomiting', 'stridor'],
    key_features_to_monitor: ['airway symptoms'],
    risk_notes: 'Dilute often mucosal irritation; concentrated product higher risk.',
    modified_release_available: false, investigation_profile: 'caustic', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'caustic_soda', name: 'Caustic soda / drain cleaner', aliases: ['caustic', 'drain cleaner', 'sodium hydroxide'], category: 'Household',
    formulations: [{ name: 'Volume (ml)', strength_mg: 1, unit: 'per_ml' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: true, hydrocarbon: false, special: 'caustic',
    specific_questions: [], observation_hrs_low: 0, observation_hrs_high: 0,
    npis_criteria: ['All significant ingestions'],
    key_features_to_monitor: ['airway', 'oral burns', 'pain'],
    risk_notes: 'Severe oesophageal injury risk — urgent surgical/endoscopy discussion.',
    modified_release_available: false, investigation_profile: 'caustic', tca: false, npis_immediate: true, high_risk_substance: true
  },
  { id: 'button_battery', name: 'Button battery', aliases: ['battery', 'cr2032', 'lithium battery'], category: 'Household',
    formulations: [{ name: 'N/A', strength_mg: 0, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'battery',
    specific_questions: [], observation_hrs_low: 0, observation_hrs_high: 0,
    npis_criteria: ['Oesophageal impaction'],
    key_features_to_monitor: ['airway', 'CXR location'],
    risk_notes: 'Not a pharmacological ingestion — location-based pathway.',
    modified_release_available: false, investigation_profile: 'battery', tca: false, npis_immediate: true, high_risk_substance: true
  },
  { id: 'magnets', name: 'Magnets (multiple)', aliases: ['magnet', 'buckyballs'], category: 'Household',
    formulations: [{ name: 'Count', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'magnet',
    specific_questions: [], observation_hrs_low: 0, observation_hrs_high: 0,
    npis_criteria: ['&gt;1 magnet or magnet + metal'],
    key_features_to_monitor: ['surgical review', 'imaging'],
    risk_notes: 'Bowel perforation/fistula risk.',
    modified_release_available: false, investigation_profile: 'surgical', tca: false, npis_immediate: true, high_risk_substance: true
  },
  { id: 'ethanol', name: 'Ethanol (alcohol)', aliases: ['ethanol', 'alcohol', 'beer', 'wine', 'vodka'], category: 'Household',
    formulations: [{ name: 'Estimate total ethanol (g) from drink', strength_mg: 1000, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 3000, serious_dose_mg_per_kg: 6000, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: 'ethanol_note',
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 4, observation_hrs_high: 8,
    npis_criteria: ['Hypoglycaemia', 'reduced GCS'],
    key_features_to_monitor: ['glucose', 'GCS'],
    risk_notes: 'Hypoglycaemia risk especially &lt;5 years; charcoal not used routinely.',
    modified_release_available: false, investigation_profile: 'ethanol', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'hydrocarbon', name: 'Petroleum / hydrocarbon liquid', aliases: ['petrol', 'kerosene', 'lamp oil', 'hydrocarbon'], category: 'Household',
    formulations: [{ name: 'Volume (ml)', strength_mg: 1, unit: 'per_ml' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: true, special: 'hydrocarbon',
    specific_questions: [], observation_hrs_low: 6, observation_hrs_high: 12,
    npis_criteria: ['Coughing', 'respiratory distress', 'CXR changes'],
    key_features_to_monitor: ['respiratory', 'aspiration risk'],
    risk_notes: 'Aspiration pneumonitis risk; do NOT induce vomiting.',
    modified_release_available: false, investigation_profile: 'hydrocarbon', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'acetone', name: 'Nail varnish remover (acetone)', aliases: ['acetone', 'nail polish remover'], category: 'Household',
    formulations: [{ name: 'Volume (ml)', strength_mg: 1, unit: 'per_ml' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 4, observation_hrs_high: 6,
    npis_criteria: ['Coma', 'severe acidosis'],
    key_features_to_monitor: ['GCS', 'ketones'],
    risk_notes: 'Relatively low systemic toxicity; aspiration if vomiting.',
    modified_release_available: false, investigation_profile: 'general', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'naphthalene', name: 'Mothballs (naphthalene)', aliases: ['naphthalene', 'mothball'], category: 'Household',
    formulations: [{ name: 'Tablets', strength_mg: 5, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 12,
    npis_criteria: ['Haemolysis', 'G6PD deficiency'],
    key_features_to_monitor: ['Hb', 'urine colour', 'renal'],
    risk_notes: 'Haemolytic risk; G6PD patients especially vulnerable.',
    modified_release_available: false, investigation_profile: 'general', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'iron', name: 'Iron supplement', aliases: ['iron', 'ferrous', 'feroglobin'], category: 'Household',
    formulations: [
      { name: 'Ferrous sulfate 200mg (~65mg elemental)', strength_mg: 65, unit: 'tablet' },
      { name: 'Ferrous fumarate 210mg (~65mg elemental)', strength_mg: 65, unit: 'tablet' },
      { name: 'Liquid (labelled elemental mg/5ml)', strength_mg: 24, unit: 'per_5ml' }
    ],
    toxic_dose_mg_per_kg: 20, serious_dose_mg_per_kg: 40, lethal_dose_mg_per_kg: null,
    antidote: 'Desferrioxamine — NPIS', antidote_fn: 'iron_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'iron',
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Serum iron', 'symptoms', 'large elemental dose'],
    key_features_to_monitor: ['iron/TIBC', 'glucose', 'FBC', 'AXR'],
    risk_notes: 'Use elemental iron for mg/kg; tablets may be radiopaque.',
    modified_release_available: false, investigation_profile: 'iron', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'cannabis', name: 'Cannabis / edibles', aliases: ['cannabis', 'thc', 'edible', 'marijuana'], category: 'Recreational',
    formulations: [{ name: 'Estimate THC dose (unknown)', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 4, observation_hrs_high: 8,
    npis_criteria: ['Prolonged reduced consciousness', 'respiratory depression'],
    key_features_to_monitor: ['HR', 'GCS', 'anxiety'],
    risk_notes: 'Titrate to symptom severity; edibles delayed onset.',
    modified_release_available: false, investigation_profile: 'general', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'mdma', name: 'MDMA / amphetamines', aliases: ['mdma', 'ecstasy', 'amphetamine', 'speed'], category: 'Recreational',
    formulations: [{ name: 'Unknown dose', strength_mg: 100, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 1, serious_dose_mg_per_kg: 3, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 6, observation_hrs_high: 12,
    npis_criteria: ['Hyperthermia', 'hyponatraemia', 'seizures'],
    key_features_to_monitor: ['temperature', 'Na+', 'CK'],
    risk_notes: 'Sympathomimetic toxidrome; hyponatraemia risk.',
    modified_release_available: false, investigation_profile: 'stimulant', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'cocaine', name: 'Cocaine', aliases: ['cocaine', 'crack'], category: 'Recreational',
    formulations: [{ name: 'Unknown', strength_mg: 50, unit: 'tablet' }],
    toxic_dose_mg_per_kg: 1, serious_dose_mg_per_kg: 2, lethal_dose_mg_per_kg: null,
    antidote: 'Benzodiazepines first-line agitation/seizures', antidote_fn: 'cocaine_note',
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: null,
    specific_questions: [], observation_hrs_low: 6, observation_hrs_high: 12,
    npis_criteria: ['Chest pain', 'arrhythmia', 'seizures', 'agitation'],
    key_features_to_monitor: ['ECG', 'BP', 'temperature'],
    risk_notes: 'Benzodiazepines first-line.',
    modified_release_available: false, investigation_profile: 'stimulant', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'unknown_rec', name: 'Unknown recreational substance', aliases: ['unknown drug', 'recreational unknown'], category: 'Recreational',
    formulations: [{ name: 'Unknown', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'unknown_rec',
    specific_questions: [], observation_hrs_low: 6, observation_hrs_high: 12,
    npis_criteria: ['Significant symptoms', 'unknown agent'],
    key_features_to_monitor: ['toxidrome pattern', 'vitals'],
    risk_notes: 'Use toxidrome checklist; NPIS if unwell.',
    modified_release_available: false, investigation_profile: 'general', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'yew', name: 'Yew (Taxus)', aliases: ['yew', 'taxus'], category: 'Plants',
    formulations: [{ name: 'Plant parts', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'yew',
    specific_questions: [], observation_hrs_low: 0, observation_hrs_high: 0,
    npis_criteria: ['All ingestions'],
    key_features_to_monitor: ['ECG', 'rhythm'],
    risk_notes: 'Highly toxic taxines; emergency.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: true, high_risk_substance: true
  },
  { id: 'foxglove', name: 'Foxglove (Digitalis)', aliases: ['foxglove', 'digitalis'], category: 'Plants',
    formulations: [{ name: 'Plant parts', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: 'Digoxin-specific antibodies — NPIS', antidote_fn: 'digoxin_note',
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'foxglove',
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['All ingestions'],
    key_features_to_monitor: ['ECG', 'K+'],
    risk_notes: 'Digoxin-like toxicity.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: true, high_risk_substance: true
  },
  { id: 'belladonna', name: 'Deadly nightshade (Atropa belladonna)', aliases: ['belladonna', 'deadly nightshade'], category: 'Plants',
    formulations: [{ name: 'Berries/leaves', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: 'Physostigmine rarely — NPIS', antidote_fn: 'anticholinergic_note',
    decontamination_eligible: true, decontamination_window_hrs: 1, charcoal_adsorbs: true, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'belladonna',
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 12,
    npis_criteria: ['Anticholinergic syndrome'],
    key_features_to_monitor: ['HR', 'temperature', 'GCS'],
    risk_notes: 'Anticholinergic toxidrome.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'berries_unknown', name: 'Berries — unknown identity', aliases: ['unknown berry', 'berries'], category: 'Plants',
    formulations: [{ name: 'Unknown', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'berries',
    specific_questions: [], observation_hrs_low: 0, observation_hrs_high: 0,
    npis_criteria: ['Cannot identify'],
    key_features_to_monitor: [],
    risk_notes: 'Use visual ID panel; if none match — NPIS.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: true, high_risk_substance: false
  },
  { id: 'ivy', name: 'Ivy', aliases: ['ivy', 'hedera'], category: 'Plants',
    formulations: [{ name: 'Leaves/berries', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'ivy',
    specific_questions: [], observation_hrs_low: 2, observation_hrs_high: 4,
    npis_criteria: ['Dermatitis', 'GI upset'],
    key_features_to_monitor: ['skin', 'GI'],
    risk_notes: 'Usually low systemic toxicity in small amounts.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'elder', name: 'Elder', aliases: ['elder', 'elderberry'], category: 'Plants',
    formulations: [{ name: 'Berries', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'elder',
    specific_questions: [], observation_hrs_low: 2, observation_hrs_high: 4,
    npis_criteria: ['Unripe berries / large amount'],
    key_features_to_monitor: ['GI'],
    risk_notes: 'Ripe cooked berries lower risk; unripe GI upset.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'holly', name: 'Holly', aliases: ['holly', 'ilex'], category: 'Plants',
    formulations: [{ name: 'Berries', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'holly',
    specific_questions: [], observation_hrs_low: 2, observation_hrs_high: 4,
    npis_criteria: ['Persistent vomiting'],
    key_features_to_monitor: ['GI'],
    risk_notes: 'Usually low systemic toxicity in small ingestions.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: false, high_risk_substance: false
  },
  { id: 'lords_ladies', name: 'Lords and ladies (Arum)', aliases: ['lords and ladies', 'arum', 'cuckoo pint'], category: 'Plants',
    formulations: [{ name: 'Berries', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'lords_ladies',
    specific_questions: [], observation_hrs_low: 4, observation_hrs_high: 8,
    npis_criteria: ['Oral irritation', 'airway swelling'],
    key_features_to_monitor: ['airway', 'pain'],
    risk_notes: 'Oxalate needles — mucosal irritation.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'monkshood', name: 'Monkshood (Aconitum)', aliases: ['monkshood', 'aconitum', 'wolfsbane'], category: 'Plants',
    formulations: [{ name: 'Any part', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'monkshood',
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['All ingestions'],
    key_features_to_monitor: ['ECG', 'rhythm', 'tingling'],
    risk_notes: 'Cardiotoxic — urgent NPIS.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: true, high_risk_substance: true
  },
  { id: 'laburnum', name: 'Laburnum', aliases: ['laburnum', 'golden chain'], category: 'Plants',
    formulations: [{ name: 'Seeds/pods', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'laburnum',
    specific_questions: [], observation_hrs_low: 8, observation_hrs_high: 12,
    npis_criteria: ['Seizures', 'GI', 'confusion'],
    key_features_to_monitor: ['GCS', 'seizures'],
    risk_notes: 'Cytisine toxicity.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: true, high_risk_substance: true
  },
  { id: 'lily_valley', name: 'Lily of the valley', aliases: ['lily of the valley', 'convallaria'], category: 'Plants',
    formulations: [{ name: 'Plant parts', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: 'Digoxin antibodies — NPIS', antidote_fn: 'digoxin_note',
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'lily_valley',
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['Bradycardia', 'hyperkalaemia'],
    key_features_to_monitor: ['ECG', 'K+'],
    risk_notes: 'Cardiac glycoside-like effects.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: true, high_risk_substance: true
  },
  { id: 'mistletoe', name: 'Mistletoe', aliases: ['mistletoe', 'viscum'], category: 'Plants',
    formulations: [{ name: 'Berries', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'mistletoe',
    specific_questions: [], observation_hrs_low: 4, observation_hrs_high: 8,
    npis_criteria: ['Bradycardia', 'hypotension'],
    key_features_to_monitor: ['HR', 'BP'],
    risk_notes: 'Viscotoxins — variable toxicity.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: false, high_risk_substance: true
  },
  { id: 'hemlock', name: 'Hemlock (Conium)', aliases: ['hemlock', 'conium', 'poison hemlock'], category: 'Plants',
    formulations: [{ name: 'Plant parts', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'hemlock',
    specific_questions: [], observation_hrs_low: 12, observation_hrs_high: 24,
    npis_criteria: ['All suspected ingestions'],
    key_features_to_monitor: ['GCS', 'respiratory depression'],
    risk_notes: 'Nicotinic toxicity — respiratory failure.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: true, high_risk_substance: true
  },
  { id: 'black_bryony', name: 'Black bryony', aliases: ['black bryony', 'tamus'], category: 'Plants',
    formulations: [{ name: 'Berries', strength_mg: 1, unit: 'tablet' }],
    toxic_dose_mg_per_kg: null, serious_dose_mg_per_kg: null, lethal_dose_mg_per_kg: null,
    antidote: null, antidote_fn: null,
    decontamination_eligible: false, decontamination_window_hrs: 0, charcoal_adsorbs: false, caustic: false, hydrocarbon: false, special: 'plant', plant_key: 'black_bryony',
    specific_questions: [], observation_hrs_low: 4, observation_hrs_high: 8,
    npis_criteria: ['Severe GI', 'dehydration'],
    key_features_to_monitor: ['GI', 'fluids'],
    risk_notes: 'Corrosive GI effects.',
    modified_release_available: false, investigation_profile: 'plant', tca: false, npis_immediate: false, high_risk_substance: true
  }
];
